### ISSUE TITLE
How can I run this example without bundling

### ISSUE THREAD

**Issue by adriatic** [stevies/aurelia-wizard-form-validation-example#3]
Trying to save my time (as I am finding out that even 14 hour days are too short for what I am trying to achieve), I would like to ask for your own "prescription" on how to reduce your sample structure to be used in this [Aurelia-Guides story](https://github.com/aurelia-guides/aurelia-guides.md-articles/blob/master/Aurelia-Applications-Development-for-JavaScript-Newbies.md) 

So, this first reduction would result with the step above [the smallest Aurelia application](https://github.com/aurelia-guides/aurelia-guides.md-articles/blob/master/Smallest-Aurelia-Application-created-from-scratch.md) or (perhaps better) replace it.

The very first thing would be to ensure that the server side while being present in the app does not need to be run - I will explain that this will come in the next more [ambitious tutorial](https://github.com/aurelia-guides/aurelia-guides.md-articles/blob/master/How-to-create-full-stack-Aurelia-Loopback-application.md).

The next reduction comes by not having to bundle (I know that you provided for this feature), but am not sure what gulp action to be used in this case.

Can you please help with these issues?

**Comment by stevies** [comment]
These are easy.   
```
The very first thing would be to ensure that the server side while being present in the app does not need to be run...
```
That is already the case.  Just run "gulp watch" - no need to run the loopback server unless you really want to.
```
The next reduction comes by not having to bundle...
```  
See above.

**Comment by adriatic** [comment]
### Just to keep you informed

What you advised was really easy to do - but it did not solve all problems I was encountering. So, in order to start from your example in the simplest possible way, without loosing any of its interesting features (at the level I want to start with it), I will also remove the ``build`` folder so I do not need to ``require`` all these

```
ar runSequence = require('run-sequence');
var changed = require('gulp-changed');
var plumber = require('gulp-plumber');
var to5 = require('gulp-babel');
var sourcemaps = require('gulp-sourcemaps');
var paths = require('../paths');
var compilerOptions = require('../babel-options');
var assign = Object.assign || require('object.assign');
var notify = require("gulp-notify");
```

and replace the original gulpfile.js with this

```
var gulp = require('gulp');
var browserSync = require('browser-sync');

// this task utilizes the browsersync plugin
// to create a dev server instance
// at http://localhost:9000
gulp.task('serve', function(done) {
  browserSync({
    open: false,
    port: 9000,
    server: {
      baseDir: ['.'],
      middleware: function (req, res, next) {
        res.setHeader('Access-Control-Allow-Origin', '*');
        next();
      }
    }
  }, done);
});
```

Besides reducing complexity, it is also obvious that I do not understand the original gulp setup - because I could not get the this line ``    <link rel="stylesheet" href="styles/styles.css">`` in the ``index.html`` to get resolved despite both ``index.html`` and ``styles`` folder being on the same level. 

![image](https://cloud.githubusercontent.com/assets/2712405/9891931/226ebd14-5bd8-11e5-890c-6822f51bcb18.png)

Clearly gulp task walks around and changes the ""current folder" as it sees fit - and I did not feel like going to relearn gulp to find what I need to change.

Note that none of this means that I do not plan to use **all features** of your example, that I find worthy of more detailed explanations in the article. So, I will deal with Gulp a bit later

**Comment by stevies** [comment]
So you are not transpiling the code and building to /dist - just trying to serve up raw ES6/7 code directly from /app?  Using http://localhost:9000/app/index.html? 

I doubt that will work.  I would have thought you would still need to build/transpile and serve up from /dist unless you plan on changing things to transpile in the browser.  And, as you say, the paths to other resources will be wrong.  

Surely much easier to just run 'gulp watch' and have a working app?

**Comment by adriatic** [comment]
I believe that you just listed sufficient number of arguments against service the app from src and transpile in the browser. This is precisely what I do not like as the key "transformational steps" get hidden. 

So, I will keep your original stucture from the get-go and activate more and more parts as we go form trivial to a complete app - which is precisely why I got so excited about your example and why I do not like the official skeleton.

So, switching to "gulp research" first, as I do not just leave it in there without proper explanations for beginners.

**Comment by stevies** [comment]
The skeleton navigation app has a simpler structure than I am using. I am not claiming mine is in any way better - just different.  And it happens to match the structure of a lot of my applications prior to aurelia and - more importantly - their build, test and deployment processes.  I've standardised on that now for my own Aurelia use, and when knocking up this example, I just used what I had to hand.

It may be that you want to stick to the following the skeleton nav project structure for your guides - most people will be familiar with that.  Please feel free to fork this project if you'd rather it was closer to the skeleton. Might save you some effort for now - you can always dig deeper into alternative project structure further down the line.  If you nee help with that, then I can advice / do the work to get it back in line.

**Comment by adriatic** [comment]
**Absolutely not :-)** I am staying with your app structure because if completely matches my previous app structures, just like you said. The only hitch I encountered is this:

I would like to delay the introduction of ``less`` (again for simplicity reasons) so I would like to do this:

**1** eliminate the step

```
gulp.task('build-less', function () {
    return gulp.src(paths.less)
        .pipe(sourcemaps.init())
        .pipe(less({
            paths: [path.join(__dirname, 'less', 'includes')],
            plugins: [cleancss]
        }))
        .pipe(sourcemaps.write('./'))
        .pipe(gulp.dest(paths.output));
});
```

from the ``build.js`` script

**2** put my own ``styles.css`` file in the ``styles`` folder as shown below:

![image](https://cloud.githubusercontent.com/assets/2712405/9894784/d6616afc-5bf5-11e5-86aa-0aa9ea5047e4.png)

**3** have the following ``head`` section in ``index.html`` file

```
<head>
    <title>Aurelia</title>
    <link rel="stylesheet" href="jspm_packages/npm/font-awesome@4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="styles/styles.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
```

The problem with this is that I am always getting the file ``styles/styles.css`` reported as missing (404) while the ``font-awesome.min.css`` has no such problem.

**Comment by adriatic** [comment]
The above assumption was correct. Now I have task 'copy-styles' instead of 'build-less' (which I will revive later of course).

Since my sample needs bootstrap and font-awesome, I managed to get them in using the same approach as Aurelia's official skeleton navigation app.However, invoking them from the code:

**app.html**
```html
<template>
  <require from="nav-bar.html"></require>
  <require from="bootstrap/css/bootstrap.css"></require>

  <nav-bar router.bind="router"></nav-bar>

  <div class="page-host">
    <router-view></router-view>
  </div>
</template>
```

**app.js**
```javascript
export class App {
  configureRouter(config, router){
    config.title = 'Aurelia';
    config.map([
      { route: ['','welcome'],  name: 'welcome',      moduleId: 'welcome',      nav: true, title:'Welcome' }
  
    ]);

    this.router = router;
  }
}
```

**main.js**
```javascript
export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging();

  aurelia.start().then(a => a.setRoot('src/app'));
}
```
**index.html**
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Aurelia</title>
    <link rel="stylesheet" href="styles/styles.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body aurelia-app="src/main">
    <!-- <div class="splash">
      <div class="message">Aurelia Navigation Skeleton</div>
      <i class="fa fa-spinner fa-spin"></i>
    </div> -->

    <script src="jspm_packages/system.js"></script>
    <script src="config.js"></script>
    <script>
      System.import('aurelia-bootstrapper');
    </script>
  </body>
</html>
```

Running gulp build creates the correct content of the dist folder

![image](https://cloud.githubusercontent.com/assets/2712405/9918783/eeb393ea-5c96-11e5-92cf-eeb43df9292c.png)

However, running this app via ``gulp serve``results with the problem - 

XHR error (404 Not Found) loading http://localhost:9000/nav-bar.html

![image](https://cloud.githubusercontent.com/assets/2712405/9918847/53636180-5c97-11e5-9266-827499345364.png)

I think that this is another gulp issue - but since the file is copied to ``dist/src`` folder I am not sure what is going on.

Can you please advise?

**Comment by stevies** [comment]
Maybe:
<require from="src/nav-bar.html"></require>
Your source is under 'src' - you need to take that into account.

**Comment by adriatic** [comment]
As it turns out, you are most likely correct, since:

```
gulp.task('serve', ['build'], function(done) {
    browserSync({
        open: false,
        port: 9000,
        server: {
            baseDir: ['./dist'],
            middleware: function (req, res, next) {
                res.setHeader('Access-Control-Allow-Origin', '*');
                next();
            }
        }
    }, done);
});
```

I need to check your app to see how do you deal with this "non-symmetric" situation (app has src folder and dist should not)

**Comment by stevies** [comment]
I have checked in a new branch with most of the build / test / deploy / less to css -stuff removed:
https://github.com/stevies/aurelia-wizard-form-validation-example/tree/complexity-removed
Check that out and just run:  
```gulp serve```
and it should work from http://localhost:9000
